// <auto-generated />
namespace SRCONFI.Projeto.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriacaoTabelas_EntradaLivros_VendaLivros_Estoque : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriacaoTabelas_EntradaLivros_VendaLivros_Estoque));
        
        string IMigrationMetadata.Id
        {
            get { return "201611271945475_CriacaoTabelas_EntradaLivros_VendaLivros_Estoque"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
